[browser]
name = chrome
headless = false
implicit_wait = 0
explicit_wait = 10

[app]
base_url = https://tutorialsninja.com/demo/
# Register this account once on the site before running valid-login tests
valid_email = gwen09781@gmail.com
valid_password =JY2VQ@gccavWCa 

[screenshots]
on_pass = true
on_fail = true